default:
 branch: 'powerkvm-v3.1.1'
 log_file: "/var/log/host-os/builds.log"
 repositories_path: "/var/lib/host-os/repositories"
 build_versions_repository_url: "https://github.com/open-power-host-os/versions.git"
 build_version: 'master'
